services:
  kafka:
    image: apache/kafka:3.7.0
    container_name: fraud-kafka
    restart: unless-stopped
    ports:
      # host-facing listener; producer.py running on your machine connects here
      - "29092:29092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://kafka:9092,CONTROLLER://kafka:9093,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
    volumes:
      - kafka_data:/var/lib/kafka/data
    healthcheck:
      test: ["CMD-SHELL", "/opt/kafka/bin/kafka-broker-api-versions.sh --bootstrap-server kafka:9092 || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 10

  postgres:
    image: postgres:16-alpine
    container_name: fraud-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: fraud
      POSTGRES_PASSWORD: fraud
      POSTGRES_DB: frauddb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fraud -d frauddb"]
      interval: 10s
      timeout: 5s
      retries: 10

  spark:
    build: ./docker/spark
    container_name: fraud-spark
    restart: unless-stopped
    depends_on:
      - kafka
      - postgres
    entrypoint: ["tail", "-f", "/dev/null"] # idle container; jobs are run via `docker compose exec spark spark-submit ...`
    volumes:
      - ./src:/opt/spark-apps
      - spark_ivy_cache:/opt/spark-ivy

volumes:
  kafka_data:
  postgres_data:
  spark_ivy_cache:
